### Necessario para pegar o token
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{
  "username": "qwe",
  "password": "qwe"
}

### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}

### teste de insercao de curso
POST http://localhost:40000/insertCurso HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "codigo": "ENG",
  "descricao": "Bacharelado em Engenharia",
  "ativo": true,
  "deleted": false
}

### teste de buscar todos os cursos
GET http://localhost:40000/getAllCursos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### teste de buscar curso por ID
GET http://localhost:40000/getCursoByID/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### teste de atualizacao de curso
PUT http://localhost:40000/updateCurso/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "codigo": "BSI-ATUAL",
  "descricao": "Bacharelado em Sistemas de Informacao Atualizado",
  "ativo": true,
  "deleted": false
}

### teste de exclusao de curso
DELETE http://localhost:40000/deleteCurso/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}
